# Generated by Django 4.1.4 on 2022-12-18 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_tags_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Post_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
