# Generated by Django 4.1.4 on 2023-01-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=10000)),
                ('image', models.ImageField(default='default.jpg', upload_to='posts/')),
            ],
        ),
    ]
